# Generated by Django 3.2.6 on 2024-10-05 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcheckout',
            name='book_id',
        ),
        migrations.AddField(
            model_name='bookcheckout',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.book'),
        ),
        migrations.AlterField(
            model_name='bookcheckout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='home.userprofile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
