# Generated by Django 3.2.6 on 2024-10-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20241006_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcheckout',
            name='book',
        ),
        migrations.AddField(
            model_name='bookcheckout',
            name='book_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
