# Generated by Django 3.2.6 on 2024-10-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20241006_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcheckout',
            name='book_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='bookcheckout',
            unique_together={('user', 'book_id')},
        ),
    ]
