# Generated by Django 3.2.6 on 2024-10-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20241006_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcheckout',
            name='book_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
