# Generated by Django 3.2.6 on 2024-10-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_bookcheckout_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcheckout',
            name='book_id',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
    ]
